#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Aplications`
nitrogen --restore &
polybar &
picom &
setxkbmap us -variant intl -model chromebook

# BSPWM
bspc monitor -d 󰊠 󰊠 󰊠 󰊠

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true