#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# AutoStart Aplications

setxkbmap us -variant intl &
nitrogen --restore 
bash ~/.config/polybar/launch.sh --blocks 
picom

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true