#!/bin/bash

sudo pacman -S vlc polybar gedit blueman bluez-utils unzip p7zip unrar tar rsync htop exfat-utils fuse-exfat curl wget trash-cli ranger thefuck tldr jdk—openjdk flatpak reflector zip unrar gnome-keyring usbutils gthumb